# Generated by Django 5.1.7 on 2025-04-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfCareSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('stressed', 'Stressed'), ('calm', 'Calm'), ('excited', 'Excited'), ('tired', 'Tired'), ('confused', 'Confused'), ('hopeful', 'Hopeful')], max_length=50)),
                ('suggestion', models.TextField()),
                ('category', models.CharField(choices=[('physical', 'Physical Activity'), ('mental', 'Mental Wellness'), ('social', 'Social Connection'), ('creative', 'Creative Expression'), ('mindfulness', 'Mindfulness')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sentimententry',
            name='emotion',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('stressed', 'Stressed'), ('calm', 'Calm'), ('excited', 'Excited'), ('tired', 'Tired'), ('confused', 'Confused'), ('hopeful', 'Hopeful')], default='neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='sentimententry',
            name='intensity',
            field=models.FloatField(default=0.0),
        ),
    ]
